version: '3'
services:
  php:
    image: php:latest
    volumes:
      - ./app:/var/www/html
    depends_on:
      - mysql
    # Add any additional PHP configuration here

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./app:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=your_password
      - MYSQL_DATABASE=your_database
      - MYSQL_USER=your_user
      - MYSQL_PASSWORD=your_password
    volumes:
      - ./mysql/data:/var/lib/mysql
    # Add any additional MySQL configuration here

  acrobat:
    image: adobe/acrobat-reader:latest
    # Add any additional configuration for Acrobat Reader here