version: '3'
services:
  phpfpm_fa:
    build:
      context: ./php-fpm
    ports:
      - "9000:9000"
    volumes:
      - ./app:/app
    links:
      - mariadb_master
    external_links:
      - nginx:fa.dev
  php:
    image: php:latest
    volumes:
      - ./app:/var/www/html
    depends_on:
      - mariadb_master
    # Add any additional PHP configuration here

  nginx:
    image: nginx:latest
    ports:
      - 8000:80
    volumes:
      - ./app:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  mariadb_master:
    image: bitnami/mariadb:latest
    environment:
      - MARIADB_ROOT_PASSWORD=dockertest
      - MARIADB_USER=dockertest
      - MARIADB_PASSWORD=dockertest
      - MARIADB_DATABASE=dockertest
    ports:
      - "3306:3306"
    volumes:
      - ./mariadb-persistence:/bitnami/mariadb
